--- 
attribution: "openrouteservice.org | OpenStreetMap contributors"
maximum_categories: 5
# meters
maximum_search_radius_for_linestrings: 2000
maximum_search_radius_for_points: 2000
maximum_search_radius_for_polygons: 2000
# square meters
maximum_area: 50000000
# meters
maximum_linestring_length: 500000
# limit of pois
response_limit: 2000
# amount of workers used for parsing the osm files
concurrent_workers: 4
# Database parameters
provider_parameters:
  table_name: ops_planet_pois
  db_name: opsdb
  user_name: postgres
  table_schema: public
  password: ops
  host: localhost
  port: 5432
  port_tests: 5432
# add any additional tags you want to save to the database
column_mappings:
  # https://wiki.openstreetmap.org/wiki/Key:name
  name:
  # https://wiki.openstreetmap.org/wiki/Key:wheelchair
  wheelchair:
  # https://wiki.openstreetmap.org/wiki/Key:smoking
  smoking:
  # https://wiki.openstreetmap.org/wiki/Key:fee
  fee:
  # https://wiki.openstreetmap.org/wiki/Key:opening_hours
  opening_hours:
  # https://wiki.openstreetmap.org/wiki/Key:phone
  phone:
  # https://wiki.openstreetmap.org/wiki/Key:website
  website:
# choose one geopy geocoder and provide all needed parameters - https://geopy.readthedocs.io/
geocoder:
#  ArcGIS:
#    domain: 'geocode.arcgis.com'
#  pelias:
#    domain: 'api.geocode.earth'
#    api_key: ''
#    timeout: 60
#  nominatim:
#    timeout: 60
#  GeocodeFarm:
#    timeout: 60
#  Azure:
#    subscription_key: ''
#    domain: 'atlas.microsoft.com'
#  Baidu:
#    api_key: ''
#  BANFrance:
#    domain: 'api-adresse.data.gouv.fr'
#  Bing:
#    api_key: ''
