language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgresql-9.5-postgis-2.4

# database creation
before_script:
  - pip install -U poetry tox-travis codecov
  - psql -c "\conninfo" -U postgres -h localhost
  - psql -c "CREATE DATABASE gis;" -U postgres -h localhost
  - psql -c "CREATE USER gis_admin WITH PASSWORD 'admin';" -U postgres -h localhost
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d gis -h localhost

script:
  - tox
