--- 
attribution: "openrouteservice.org | OpenStreetMap contributors"
osmium_strategy: flex_mem  # see osmium settings here: https://osmcode.org/osmium-concepts/#list-of-map-index-classes
concurrent_workers: 3  # recommended: available cores - 1
maximum_categories: 5
maximum_search_radius_for_linestrings: 2000  # meters
maximum_search_radius_for_points: 2000  # meters
maximum_search_radius_for_polygons: 2000  # meters
maximum_area: 50000000  # square meters
maximum_linestring_length: 500000  # meters
response_limit: 2000  # limit of pois
provider_parameters:
  table_name: ops_planet_pois
  db_name: gis
  user_name: gis_admin
  table_schema: public
  password: admin
  host: localhost
  port: 5432
# add or remove OSM keys you want to save to the database
column_mappings:
  # https://wiki.openstreetmap.org/wiki/Key:name
  name:
  # https://wiki.openstreetmap.org/wiki/Key:wheelchair
  wheelchair:
  # https://wiki.openstreetmap.org/wiki/Key:smoking
  smoking:
  # https://wiki.openstreetmap.org/wiki/Key:fee
  fee:
  # https://wiki.openstreetmap.org/wiki/Key:opening_hours
  opening_hours:
  # https://wiki.openstreetmap.org/wiki/Key:phone
  phone:
  # https://wiki.openstreetmap.org/wiki/Key:website
  website:
